// @ts-check
/**
 * Shared LavaMoat lockdown + scuttle options for extension bundles.
 * Scuttling strips the real globalThis after endowments are copied into compartments.
 */

/** @type {Record<string, string>} */
const lockdown = {
  consoleTaming: 'unsafe',
  errorTaming: 'unsafe',
  stackFiltering: 'verbose',
  overrideTaming: 'severe',
  localeTaming: 'unsafe',
  errorTrapping: 'none',
  reporting: 'none',
};

/** Globals the MV3 service worker (and webpack runtime) still need after scuttle. */
const backgroundScuttleExceptions = [
  'chrome',
  'browser',
  'self',
  'globalThis',
  'console',
  'performance',
  'setTimeout',
  'clearTimeout',
  'setInterval',
  'clearInterval',
  'queueMicrotask',
  'structuredClone',
  'atob',
  'btoa',
  'crypto',
  'fetch',
  'Response',
  'Request',
  'Headers',
  'URL',
  'URLSearchParams',
  'TextEncoder',
  'TextDecoder',
  'AbortController',
  'AbortSignal',
  'BroadcastChannel',
  'importScripts',
  'clients',
  'registration',
  'caches',
  'indexedDB',
  'Proxy',
  'Reflect',
  'Promise',
  'Object',
  'Array',
  'Map',
  'Set',
  'WeakMap',
  'WeakSet',
  'Symbol',
  'JSON',
  'Math',
  'Date',
  'Number',
  'String',
  'Boolean',
  'Error',
  'TypeError',
  'RangeError',
  'Uint8Array',
  'ArrayBuffer',
  'DataView',
  /Uint[0-9]+Array/,
  /Int[0-9]+Array/,
  'Float32Array',
  'Float64Array',
  'BigInt',
  'parseInt',
  'parseFloat',
  'isNaN',
  'Infinity',
  'NaN',
  'undefined',
  'Function',
  'RegExp',
  'Intl',
  'encodeURIComponent',
  'decodeURIComponent',
  'encodeURI',
  'decodeURI',
];

/**
 * Globals the popup/side-panel needs after scuttle (React + Chrome extension APIs).
 * Compartment isolation still applies; these stay reachable on the real globalThis.
 */
const popupScuttleExceptions = [
  ...backgroundScuttleExceptions,
  'window',
  'document',
  'navigator',
  'location',
  'history',
  'localStorage',
  'sessionStorage',
  'getComputedStyle',
  'getSelection',
  'matchMedia',
  'requestAnimationFrame',
  'cancelAnimationFrame',
  'requestIdleCallback',
  'cancelIdleCallback',
  'innerWidth',
  'innerHeight',
  'outerWidth',
  'outerHeight',
  'devicePixelRatio',
  'pageXOffset',
  'pageYOffset',
  'scrollX',
  'scrollY',
  'visualViewport',
  'Image',
  'MutationObserver',
  'ResizeObserver',
  'IntersectionObserver',
  'CustomEvent',
  'Event',
  'EventTarget',
  'Node',
  'Element',
  'HTMLElement',
  'HTMLIFrameElement',
  'HTMLInputElement',
  'HTMLFormElement',
  'HTMLCanvasElement',
  'SVGElement',
  'Document',
  'DocumentFragment',
  'Text',
  'Comment',
  'DOMRect',
  'CSS',
  'ShadowRoot',
  'customElements',
  'MessageChannel',
  'MessagePort',
  'Blob',
  'File',
  'FileReader',
  'FormData',
  'Worker',
  'SharedWorker',
  'WebSocket',
  'XMLHttpRequest',
  'OffscreenCanvas',
  'Path2D',
  'focus',
  'blur',
  'scrollTo',
  'scrollBy',
  'open',
  'close',
  'postMessage',
  'addEventListener',
  'removeEventListener',
  'dispatchEvent',
  'name',
  'length',
  'origin',
  'isSecureContext',
  'reportError',
  'screen',
  'CSSStyleSheet',
  'HTMLDivElement',
  'HTMLSpanElement',
  'HTMLButtonElement',
  'HTMLAnchorElement',
  'HTMLImageElement',
  'HTMLTextAreaElement',
  'HTMLSelectElement',
  'HTMLOptionElement',
  'HTMLLabelElement',
  'KeyboardEvent',
  'MouseEvent',
  'PointerEvent',
  'TouchEvent',
  'WheelEvent',
  'FocusEvent',
  'InputEvent',
  'CompositionEvent',
  'ClipboardEvent',
  'DragEvent',
  'AnimationEvent',
  'TransitionEvent',
];

module.exports = {
  lockdown,
  backgroundScuttleExceptions,
  popupScuttleExceptions,
};
